### ISSUE TITLE
store data in memory structures instead of XML

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#124]
> @h1alexbel I have a general question. Why we need `sql` database? I think if we're choosing in memory solution we can use just some list(or any other collection) of data structs. IMHO it would be much simpler then have some `sql` storage. No requests needed. Need to add/remove something – just call `github#add_user`/`github#add_repo` and etc. If we need some history of changes we can build some state machine that will track all changes that was made by user and it would build report based on it's history

@l3r8yJ I thought about that. We can create some data structures in memory and operate with them. In the end we should obtain a hierarchy of these structures.

_Originally posted by @h1alexbel in https://github.com/h1alexbel/fakehub/issues/123#issuecomment-2315103122_

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#134](https://github.com/h1alexbel/fakehub/issues/134), [#135](https://github.com/h1alexbel/fakehub/issues/135) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#135](https://github.com/h1alexbel/fakehub/issues/135) is still not solved; solved: [#134](https://github.com/h1alexbel/fakehub/issues/134).
