### ISSUE TITLE
internal endpoint for user account creation

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#17]
On the public GitHub API [there is no ability](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28) to create GitHub account, however we should provide this ability in our API. I suggest to create an endpoint `POST /users` with body like this: `username` + `password` that will create a user account.

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by h1alexbel** [comment]
I'm in

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#73](https://github.com/h1alexbel/fakehub/issues/73), [#74](https://github.com/h1alexbel/fakehub/issues/74), [#75](https://github.com/h1alexbel/fakehub/issues/75) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#73](https://github.com/h1alexbel/fakehub/issues/73), [#98](https://github.com/h1alexbel/fakehub/issues/98), [#99](https://github.com/h1alexbel/fakehub/issues/99) are still not solved; solved: [#74](https://github.com/h1alexbel/fakehub/issues/74), [#75](https://github.com/h1alexbel/fakehub/issues/75).

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#101](https://github.com/h1alexbel/fakehub/issues/101), [#73](https://github.com/h1alexbel/fakehub/issues/73), [#98](https://github.com/h1alexbel/fakehub/issues/98), [#99](https://github.com/h1alexbel/fakehub/issues/99) are still not solved; solved: [#74](https://github.com/h1alexbel/fakehub/issues/74), [#75](https://github.com/h1alexbel/fakehub/issues/75).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#101](https://github.com/h1alexbel/fakehub/issues/101) is still not solved; solved: [#73](https://github.com/h1alexbel/fakehub/issues/73), [#74](https://github.com/h1alexbel/fakehub/issues/74), [#75](https://github.com/h1alexbel/fakehub/issues/75), [#98](https://github.com/h1alexbel/fakehub/issues/98), [#99](https://github.com/h1alexbel/fakehub/issues/99).

**Comment by 0pdd** [comment]
@h1alexbel all 6 puzzles are solved here: [#101](https://github.com/h1alexbel/fakehub/issues/101), [#73](https://github.com/h1alexbel/fakehub/issues/73), [#74](https://github.com/h1alexbel/fakehub/issues/74), [#75](https://github.com/h1alexbel/fakehub/issues/75), [#98](https://github.com/h1alexbel/fakehub/issues/98), [#99](https://github.com/h1alexbel/fakehub/issues/99).
