### ISSUE TITLE
how to generate open api clients

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#35]
first, install generator like that (npm required):

```bash
npm install @openapitools/openapi-generator-cli -g
```

then execute:

```bash
openapi-generator-cli generate -i api.yml -g rust -o .
```

now, you should have the following structure:

```text
src/
  /apis
   mod.rs
   configuration.rs
   default_api.rs
  /models
    mod.rs
    foo.rs
  lib.rs
Cargo.toml
.openapi-generator-ignore
...
```

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, we need to design in which directory we gonna place those generated structs and funcs

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#57](https://github.com/h1alexbel/fakehub/issues/57) is still not solved.
