### ISSUE TITLE
Generate report.tex with all interaction history with fakehub

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#41]
Let's generate `report.tex` file that will contain all the history of interaction with our tool during the particular run session. We can even render a nice PDF document from that tex file if user pass `--report` flag within `start` command.

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel i think report might be in different formats, for example these args can be supported

1. `--xml`
2. `--tex`
3. `--txt`

wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ yes, good idea. We can combine these options with `--report` flag

**Comment by l3r8yJ** [comment]
@h1alexbel let's do it in form of `fakehub start --report <FORMAT>` i.e. with `tex` it will be look like this: `fakehub start --report tex`, wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ looks good, let's do this

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#52](https://github.com/h1alexbel/fakehub/issues/52), [#53](https://github.com/h1alexbel/fakehub/issues/53), [#54](https://github.com/h1alexbel/fakehub/issues/54), [#55](https://github.com/h1alexbel/fakehub/issues/55) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#52](https://github.com/h1alexbel/fakehub/issues/52), [#53](https://github.com/h1alexbel/fakehub/issues/53), [#55](https://github.com/h1alexbel/fakehub/issues/55) are still not solved; solved: [#54](https://github.com/h1alexbel/fakehub/issues/54).
