### ISSUE TITLE
add `--init` flag

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#45]
from #13: let's add a `--bootstrap` flag for setup of the initial state of fake GitHub API

**Comment by h1alexbel** [comment]
@l3r8yJ How about to create a DSL, or a small language that will allow us to write something like this:

```text
github: main
user: @jeff
+repo jeff/foo (+issue ("first issue" +label "bug") )
+repo jeff/bar
```

this file will be processed by some "parser" and "runtime", and all entities created in main GitHub (which is `https://github.com`). WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ I think we can develop this functionality in separate repo, in order to [keep repos small](https://www.yegor256.com/2018/09/05/monolithic-repositories.html). WDYT?

**Comment by h1alexbel** [comment]
Here is more examples:

```text
github: main
me: @jeff
+repo me/foo (+issue ("first issue" +label "bug") )
+repo me/bar (+issue ("first issue as well" +body "it is first issue in this repo" ) )
+issue ("testing", +label "question") in me/bar
me: @mary
+pull ("1", _) in @jeff/foo
```

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#202](https://github.com/h1alexbel/fakehub/issues/202) is still not solved.
