### ISSUE TITLE
latex.rs:53-56: Add support of @ExtendsWith from JUnit in...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/fakehub#54]
The puzzle `41-8e9aa4b2` from #41 has to be resolved: 

https://github.com/h1alexbel/fakehub/blob/fe9cf78769e95b1d2a27a298988922a95950044b/server/src/report/latex.rs#L53-L56

The puzzle was created by @h1alexbel on 26-Jun-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
> @0pdd thanks for the report, here is a feedback: * The todo seems to be asking for adding support of...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by h1alexbel** [comment]
@l3r8yJ can you help here?
