### ISSUE TITLE
release 0.0.1

### ISSUE THREAD

**Issue by l3r8yJ** [h1alexbel/fakehub#6]
just empty release, via `rultor`

**Comment by l3r8yJ** [comment]
blocked by #9

**Comment by h1alexbel** [comment]
@l3r8yJ let me work on this

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor stop

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor stop

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor stop

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.2`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.2`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.3`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.4`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.5`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.5`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
need to wait some time, getting `502` from npm repo

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.5`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.6`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.7`
