### ISSUE TITLE
user.rs:44-46: Configure clippy to reject code with...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/fakehub#74]
The puzzle `17-e45e524d` from #17 has to be resolved: 

https://github.com/h1alexbel/fakehub/blob/31636e6ff542ff1317c28ae7bbac232572a06a30/server/src/objects/user.rs#L44-L46

The puzzle was created by @h1alexbel on 11-Jul-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
> @0pdd thanks for the report, here is a feedback: * Avoid using `#unwrap()` method as it may cause a ...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by h1alexbel** [comment]
@l3r8yJ can you help here?

**Comment by l3r8yJ** [comment]
@h1alexbel sure

**Comment by 0pdd** [comment]
@0pdd the puzzle [#101](https://github.com/h1alexbel/fakehub/issues/101) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#101](https://github.com/h1alexbel/fakehub/issues/101) is solved here.
