### ISSUE TITLE
implement `stop` to shutdown fakehub server

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#77]
Let's think how we would implement `fakehub stop` command in order to stop the server. Moreover, we should think about test setup that users will utilize. Consider this script as test fixture:

```bash
fakehub start # server bootstrap
# invoking some test suite...
fakehub stop # server shutdown
```

@l3r8yJ any ideas how to implement such operation?

**Comment by h1alexbel** [comment]
I think we should somehow trigger server stop from the code. Let's find out is it possible

**Comment by h1alexbel** [comment]
Depends on #129

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#193](https://github.com/h1alexbel/fakehub/issues/193), [#194](https://github.com/h1alexbel/fakehub/issues/194), [#195](https://github.com/h1alexbel/fakehub/issues/195) are still not solved.
