### ISSUE TITLE
return `openapi::models::MetaRoot200Response` from home endpoint

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#79]
We should return generated `openapi::models::MetaRoot200Response` struct from our home endpoint, instead of using json file located in `server/resources/home.json`. Other endpoints will updated respectively using the same approach.

**Comment by 0pdd** [comment]
@h1alexbel 6 puzzles [#82](https://github.com/h1alexbel/fakehub/issues/82), [#83](https://github.com/h1alexbel/fakehub/issues/83), [#84](https://github.com/h1alexbel/fakehub/issues/84), [#85](https://github.com/h1alexbel/fakehub/issues/85), [#86](https://github.com/h1alexbel/fakehub/issues/86), [#87](https://github.com/h1alexbel/fakehub/issues/87) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#82](https://github.com/h1alexbel/fakehub/issues/82), [#83](https://github.com/h1alexbel/fakehub/issues/83), [#85](https://github.com/h1alexbel/fakehub/issues/85), [#86](https://github.com/h1alexbel/fakehub/issues/86), [#87](https://github.com/h1alexbel/fakehub/issues/87) are still not solved; solved: [#84](https://github.com/h1alexbel/fakehub/issues/84).

**Comment by 0pdd** [comment]
@h1alexbel 6 puzzles [#105](https://github.com/h1alexbel/fakehub/issues/105), [#82](https://github.com/h1alexbel/fakehub/issues/82), [#83](https://github.com/h1alexbel/fakehub/issues/83), [#85](https://github.com/h1alexbel/fakehub/issues/85), [#86](https://github.com/h1alexbel/fakehub/issues/86), [#87](https://github.com/h1alexbel/fakehub/issues/87) are still not solved; solved: [#84](https://github.com/h1alexbel/fakehub/issues/84).

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#105](https://github.com/h1alexbel/fakehub/issues/105), [#83](https://github.com/h1alexbel/fakehub/issues/83), [#85](https://github.com/h1alexbel/fakehub/issues/85), [#86](https://github.com/h1alexbel/fakehub/issues/86), [#87](https://github.com/h1alexbel/fakehub/issues/87) are still not solved; solved: [#82](https://github.com/h1alexbel/fakehub/issues/82), [#84](https://github.com/h1alexbel/fakehub/issues/84).
