### ISSUE TITLE
formulate requirements

### ISSUE THREAD

**Issue by l3r8yJ** [h1alexbel/fakehub#9]
@h1alexbel i think we need to have a precise list of features for `0.0.1` version

**Comment by h1alexbel** [comment]
@l3r8yJ I think here is the list:

* Full GitHub API mirror with help of Open API contracts
* Web server that with mirrored endpoints
* JSON responses from fake API
* XML storage
* cli tool, for instance `fakehub`, that would support `start` and `stop` commands

in the next versions we can try to render nice HTML pages from XML storage that we have.

WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ if it looks good, I can open separate issues for each of the points

**Comment by l3r8yJ** [comment]
@h1alexbel i think for ‘0.0.1’ version, we can’t afford all endpoints, i suppose that we need to specify a precise list of endpoints to support

**Comment by h1alexbel** [comment]
@l3r8yJ Yes, in `0.0.1` we should implement most required functions, like repositories, pulls, issues (I will craft a list a bit later). Though, we still should mirror all the endpoints GitHub API currently supports. We can stub non-0.0.1 functions, and incrementally implement them in future releases. WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel sure, but i think we need to group them by milestones

**Comment by h1alexbel** [comment]
@l3r8yJ let's start with these functions:

* public GitHub instance
* users
* repositories
* pull requests
* issues
* git (objects, file, blobs)

WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ updated list with more precise functions

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#28](https://github.com/h1alexbel/fakehub/issues/28) is still not solved.

**Comment by h1alexbel** [comment]
@l3r8yJ created issues for concrete endpoints. I think in version 0.0.1 we can omit blobs, commits, and 
file trees. WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel okay

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#28](https://github.com/h1alexbel/fakehub/issues/28) is solved here.
